[project]
requires-python = ">=3.8"

[project.optional-dependencies]
dev=["ruff", "pyright"]

[tool.ruff]
required-version = ">=0.9.10"
respect-gitignore = true
exclude = [".git",".github", "./docs", "kiauh/core/submodules"]
line-length = 88
indent-width = 4
output-format = "full"
target-version = "py38"

[tool.ruff.format]
indent-style = "space"
line-ending = "lf"
quote-style = "double"

[tool.ruff.lint]
extend-select = ["I"]
